version: '3.8'

services:
  # PostgreSQL service with security
  postgres:
    image: postgres:15-alpine
    container_name: apae-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-apae_db}
      POSTGRES_USER: ${POSTGRES_USER:-apae_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apae_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - apae-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-apae_user} -d ${POSTGRES_DB:-apae_db}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MinIO service with security
  minio:
    image: minio/minio:latest
    container_name: apae-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
    volumes:
      - minio_data:/data
    networks:
      - apae-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Application service with security
  app:
    image: apae-app:latest
    container_name: apae-app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-apae_user}:${POSTGRES_PASSWORD:-apae_password}@postgres:5432/${POSTGRES_DB:-apae_db}
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minioadmin123}
      - NODE_ENV=production
    networks:
      - apae-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/.next
    depends_on:
      - postgres
      - minio

  # Nginx with security
  nginx:
    image: nginx:alpine
    container_name: apae-nginx
    volumes:
      - ./nginx-security.conf:/etc/nginx/nginx.conf
    networks:
      - apae-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run
    ports:
      - "80:80"
      - "443:443"

  # Fail2ban for security
  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: apae-fail2ban
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./fail2ban:/config
      - /var/log:/var/log:ro
    networks:
      - apae-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_ADMIN
      - NET_RAW

  # UFW firewall
  ufw:
    image: ubuntu:22.04
    container_name: apae-ufw
    volumes:
      - ./ufw:/etc/ufw
    networks:
      - apae-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_ADMIN
    command: |
      sh -c "
        apt-get update && apt-get install -y ufw
        ufw --force enable
        ufw default deny incoming
        ufw default allow outgoing
        ufw allow 22/tcp
        ufw allow 80/tcp
        ufw allow 443/tcp
        ufw allow 5432/tcp
        ufw allow 9000/tcp
        ufw allow 9001/tcp
        ufw --force reload
        tail -f /dev/null
      "

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  apae-network:
    driver: bridge
