server {
    listen 80;

    # 🔹 Frontend
    location /apae-geral {
        proxy_pass http://apae-geral-frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 🔹 Site comemorativo
    location /site-comemorativo/ {
        proxy_pass http://app:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /gestao-escolar/api {
        proxy_pass http://gestao-escolar-backend:8080;
    }

    location /gestao-escolar {
    proxy_pass http://gestao-escolar-frontend:3000/gestao-escolar;
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme; 
    }
}