name: SonarQube Analysis

on:
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  sonar-frontend:
    name: Frontend Analysis (Node)
    uses: IFPBEsp/APAE-INFRA/.github/workflows/reusable-sonarqube-node.yml@dev
    with:
      project-key: "apae-site-comemorativo-frontend"
      organization: "ifpbesp"
      working-directory: "."
      node-version: "22"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
