name: SonarQube Analysis

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  call-sonar-fullstack:
    uses: IFPBEsp/APAE-INFRA/.github/workflows/reusable-sonarqube-fullstack.yml@dev
    with:
      backend-project-key: "apae-site-comemorativo-backend"
      frontend-project-key: "apae-site-comemorativo-frontend"
      backend-dir: "." 
      frontend-dir: "."
      organization: "ifpbesp"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}