name: SonarQube Analysis

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

permissions:
  contents: read

jobs:
  sonar-frontend:
    name: Frontend Analysis (Node)
    uses: IFPBEsp/APAE-INFRA/.github/workflows/reusable-sonarqube-node.yml@dev
    with:
      project-key: "apae-site-comemorativo-frontend"
      organization: "ifpbesp"
      working-directory: "src"
      node-version: "22"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
